"""Bake the Entanglement Shader reflectance/transmittance LUTs (Moth Atlas job entanglement-shader-v1,
9214cb9d) into src/ShellLut.hpp for the egg UI.

The engine ships R_lut.hdr / T_lut.hdr as single-channel float data stored in RGB. They are packed into one
RGBA8 texture (R in red, T in green, both scaled by 1/kLutScale) so it uploads on any OpenGL 2 context.
"""
from pathlib import Path
import sys

import numpy as np

HERE = Path(__file__).resolve().parent
PLUGIN = HERE.parent
sys.path.insert(0, str(PLUGIN.parent / "three"))
import prep_data  # noqa: E402  (reuses the reader that the web viewer is built with)

SCALE = 2.0


def main():
    R = prep_data.read_hdr(prep_data.SHADER_DIR / "R_lut.hdr")[..., 0]
    T = prep_data.read_hdr(prep_data.SHADER_DIR / "T_lut.hdr")[..., 0]
    assert R.shape == T.shape
    h, w = R.shape
    rgba = np.zeros((h, w, 4), np.uint8)
    rgba[..., 0] = np.clip(np.round(R / SCALE * 255), 0, 255)
    rgba[..., 1] = np.clip(np.round(T / SCALE * 255), 0, 255)
    rgba[..., 3] = 255
    data = rgba.reshape(-1)
    lines = [", ".join(str(int(v)) for v in data[i:i + 32]) for i in range(0, len(data), 32)]
    out = PLUGIN / "src" / "ShellLut.hpp"
    out.write_text(
        "// Generated by tools/export_lut.py from three/engine_outputs/shader_9214cb9d (do not edit).\n"
        "// Entanglement Shader (Moth Atlas entanglement-shader-v1, job %s): R in red, T in green,\n"
        "// value = byte / 255 * kLutScale. Rows are t = theta / (pi/2), columns the film phase s.\n"
        "#pragma once\n\nnamespace se {\n\n"
        "constexpr int kLutW = %d, kLutH = %d;\nconstexpr float kLutScale = %.1ff;\n"
        "constexpr const char* kLutJob = \"%s\";\n"
        "static const unsigned char kShellLut[] = {\n%s\n};\n\n}  // namespace se\n"
        % (prep_data.SHADER_JOB, w, h, SCALE, prep_data.SHADER_JOB, ",\n".join(lines)),
        encoding="utf-8")
    print(f"wrote {out} ({w}x{h}, R {R.min():.3f}..{R.max():.3f}, T {T.min():.3f}..{T.max():.3f})")


if __name__ == "__main__":
    main()
