"""Export measured otoc-echo-v1 tap maps into plugin presets.

Reads plugin/tools/measured.json (written by measure.py), writes:
  plugin/presets/<NN>_<name>.json   human-readable preset (same "taps" schema as the engine's extras.taps)
  plugin/src/Presets.hpp            the same JSON embedded in the binary
  plugin/presets/maps.png           Re F(site, t) heatmaps of every preset

    .venv\\Scripts\\python plugin\\tools\\export_presets.py
"""
import json
import math
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
PLUGIN = HERE.parent
ROOT = PLUGIN.parent
sys.path.insert(0, str(ROOT))
import fmap  # noqa: E402

# Order = the plugin's Map menu. Index 0 is also the fixed Scramble=0 end.
PRESETS = [
    ("control_clifford", "Control (Clifford)",
     "theta_zz = pi: every layer is a Clifford circuit, so the kicked Pauli is mapped to another single Pauli "
     "string and does not spread into a superposition of operators. No scrambling: every tap stays at |F| = 1 "
     "(the kick site itself at F = -1, an inverted echo)."),
    ("low_theta_x", "Low theta_x",
     "Weak transverse drive (theta_x = 0.1 pi): the operator barely spreads, most taps stay loud and positive."),
    ("sparse", "Sparse",
     "theta_zz = 0.25 pi, the engine's sparse coupling setting: a thin light cone with few strong taps."),
    ("scrambling", "Scrambling",
     "theta_x = 0.3 pi, theta_zz = 0.35 pi: the operator spreads through a light cone from the kick site; "
     "inside it F decays and flips sign (inverted echoes). Finite-size revival around t = 13-16 on 12 sites."),
    ("phase", "Phase (complex F)",
     "Scrambling settings plus theta_z = 0.25 pi, which makes F complex. The plugin uses |F| as gain and the sign "
     "of Re F as polarity; the phase itself is not rendered."),
    ("disorder", "Disorder",
     "Scrambling settings with per-gate angle jitter (std 0.6 rad, seed 7), which localises the echo."),
    ("wide14_d16", "Wide (14 sites)",
     "Scrambling settings on a 14-site chain, depth 16 (wider stereo field, shorter train)."),
    ("kick_left", "Kick left (site 2)",
     "Scrambling settings with the kick on site 2: the chain's mirror symmetry is broken, so the light cone "
     "and the inverted echoes move from left to right across the stereo field."),
    ("edge_sparse", "Edge kick, sparse (site 0)",
     "Sparse coupling (theta_zz = 0.25 pi) kicked at the left edge: the light cone runs diagonally across the "
     "chain and reflects off the far end, a measured stereo ping-pong."),
]


def load_record(info):
    return json.loads((ROOT / info["path"]).read_text(encoding="utf-8"))


def preset_of(key, title, desc, info):
    rec = load_record(info)
    F, ex = fmap.load_F(rec)
    p = ex["params"]
    taps = [{"site": int(s), "depth": int(t + 1), "F_re": round(float(F[s, t].real), 6),
             "F_im": round(float(F[s, t].imag), 6)}
            for s in range(F.shape[0]) for t in range(F.shape[1])
            if abs(F[s, t]) >= 1e-4 and np.isfinite(F[s, t])]
    return {
        "name": title,
        "description": desc,
        "source": {"engine": "otoc-echo-v1", "job_id": rec["job_id"], "machine": p["machine"],
                   "exact": p["exact"], "note": "Moth Atlas, aer emulator (noiseless, exact expectation values)",
                   "params": {k: p[k] for k in ("n_sites", "depth", "theta_x", "theta_z", "theta_zz",
                                                 "disorder", "seed", "kick", "lattice") if k in p}},
        "n_sites": int(F.shape[0]),
        "depth": int(F.shape[1]),
        "kick_site": int(ex["kick_site"]),
        "taps": taps,
    }, F


def cxx_header(presets):
    lines = ["// Generated by plugin/tools/export_presets.py from measured otoc-echo-v1 runs. Do not edit.",
             "#pragma once", "", "namespace se {", "",
             "struct EmbeddedPreset { const char* key; const char* json; };", "",
             "static const EmbeddedPreset kPresets[] = {"]
    for key, pre in presets:
        text = json.dumps(pre, separators=(",", ":"))
        chunks = [text[i:i + 8000] for i in range(0, len(text), 8000)]
        body = "\n".join(f'        R"SEJSON({c})SEJSON"' for c in chunks)
        lines.append(f'    {{"{key}",\n{body}}},')
    lines += ["};", "", "static constexpr int kNumPresets = (int) (sizeof(kPresets) / sizeof(kPresets[0]));",
              "", "}  // namespace se", ""]
    return "\n".join(lines)


def heatmaps(named, path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    cols = 4
    rows = math.ceil(len(named) / cols)
    fig, axes = plt.subplots(rows, cols, figsize=(4.2 * cols, 3.2 * rows), squeeze=False)
    for ax in axes.flat:
        ax.axis("off")
    for ax, (title, F) in zip(axes.flat, named):
        ax.axis("on")
        ax.imshow(F.real, aspect="auto", cmap="RdBu", vmin=-1, vmax=1,
                  extent=[0.5, F.shape[1] + 0.5, F.shape[0] - 0.5, -0.5])
        ax.set_title(title, fontsize=10)
        ax.set_xlabel("echo step t (delay)")
        ax.set_ylabel("site (pan)")
    fig.suptitle("Scrambled Echo presets: Re F(site, t) from otoc-echo-v1 (blue = +1, red = -1: inverted echo)")
    fig.tight_layout()
    fig.savefig(path, dpi=110)


if __name__ == "__main__":
    measured = json.loads((HERE / "measured.json").read_text(encoding="utf-8"))
    out_dir = PLUGIN / "presets"
    out_dir.mkdir(exist_ok=True)
    for old in out_dir.glob("*.json"):
        old.unlink()
    built, named = [], []
    for i, (key, title, desc) in enumerate(PRESETS):
        if key not in measured:
            print(f"skip {key}: not measured")
            continue
        pre, F = preset_of(key, title, desc, measured[key])
        (out_dir / f"{i:02d}_{key}.json").write_text(json.dumps(pre, indent=1), encoding="utf-8")
        built.append((key, pre))
        named.append((title, F))
        a = np.abs(F)
        print(f"{key:18s} job {pre['source']['job_id'][:8]} grid {F.shape} taps {len(pre['taps']):4d} "
              f"sum|F| {a.sum():7.2f} |F|>0.99 {int((a > 0.99).sum()):4d} inverted {int((F.real < -1e-4).sum()):4d}")
    (PLUGIN / "src" / "Presets.hpp").write_text(cxx_header(built), encoding="utf-8")
    heatmaps(named, out_dir / "maps.png")
